Spring:
  datasource:
      password: Dolomiti99
      url: jdbc:mysql://localhost:3306/db2
      username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  batch:
    job:
      enabled: false